"use client";

import { signIn, useSession, signOut } from "next-auth/react";
import Head from "next/head";
import Menu from '@/src/components/Menu.jsx'
import Busqueda from '@/src/components/Busqueda'
import styles from '@/src/app/styles/Home.module.css'
import { Fredoka } from 'next/font/google'
import { useRouter } from "next/navigation";

const fredoka = Fredoka({ subsets: ['latin'], weight: '300', width: 110 })

function Navbar() {
  const { data: session } = useSession();
  const router = useRouter()

  return (
    
    <nav className={styles.nav}>
      <Head>
        <title> B.A.T </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/LogoB.png/" />
      </Head>
      <div style={fredoka.style} className={styles.header}>
        <div className={styles.left}>
          <a href="" className={styles.menu} ><Menu width={24} height={23} /></a>
          <a href="/"> <img className={styles.logo} src="logoLanding.png" /></a>
        </div>
        <div className={styles.center}>
          <a className={styles.nos} href="/nosotros">NOSOTROS</a>
          <a className={styles.sub} href="/datos">DATOS</a>
          <a className={styles.cont} href="/contacto">CONTACTO</a>
        </div>
        <div className={styles.right}>
          {session?.user ? (
            <div className="flex gap-x-2 items-center">
              <button className={styles.logOut}
                onClick={async () => {
                  await signOut({
                    callbackUrl: "/",
                  })
                }}
              >
                Logout
              </button>
              <img className={styles.Profile}
                src={session.user.image ?? ""}
                alt=""
               
              />
              
            </div>
          ) : (
            <button
              onClick={() => signIn(undefined, { callbackUrl: "/datos" })}
                style={fredoka.style} className={styles.log}
            >
              Log In
            </button>
          )}
          <a href="" className={styles.lupa}><Busqueda width={24} height={23} /></a>
        </div>
      </div>
    </nav>
  );
}
export default Navbar;
